SUBSCRIPTION_START = (6, 1)
SUBSCRIPTION_END = (5, 31)
ANNUAL_SUBSCRIPTION_AMOUNT = 700 * 100
SPONSORED_ANNUAL_SUBSCRIPTION_AMOUNT = 200 * 100
EVENT_SUBSCRIPTION_AMOUNT = 375 * 100
MAJOR_AGE = 18

# How long a duplicate-account claim link stays valid.
CLAIM_TOKEN_DAYS = 14
