#!/bin/bash

set -euo pipefail

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -t|--target)
            TARGET="$2"
            shift
            shift
            ;;
        *)
            echo "Error: Unknown option $1"
            exit 1
            ;;
    esac
done

# Check if the target is specified
if [[ -z $TARGET ]]; then
    echo "Error: Deployment target not specified. Use -t or --target option to specify the target (production or staging)."
    exit 1
fi

# Get the current branch name
CURRENT_BRANCH=$(git symbolic-ref --short HEAD)
# Check if deploying to production and the current branch is not main
if [[ $TARGET == "production" && $CURRENT_BRANCH != "main" ]]; then
    echo "Error: You can only deploy to production from the 'main' branch."
    exit 1
fi

# Check if there are uncommitted changes
if [[ $(git diff --shortstat 2> /dev/null | tail -n1) != "" ]]; then
    if [[ $TARGET == "production" ]]; then
        echo "ERROR: There are uncommitted changes in your current branch."
        exit 1
    else
        echo "WARN: There are uncommitted changes in your current branch."
    fi
fi

# Deploy the app based on the specified target
case $TARGET in
    production)
        CONFIG_FILE="fly.toml"
        ;;
    staging)
        CONFIG_FILE="fly.staging.toml"
        ;;
    *)
        echo "Error: Invalid deployment target. Supported targets are 'production' and 'staging'."
        exit 1
        ;;
esac

# Deploy the app using flyctl
echo "Deploying to $TARGET..."
flyctl deploy -c $CONFIG_FILE --local-only
flyctl ssh console -c $CONFIG_FILE -u user -C 'python manage.py check --deploy'

if [[ $TARGET == "staging" ]]; then
    flyctl ssh console -c fly.staging.toml -u user -C 'python manage.py loaddata server/fixtures/sample_data.json'
fi

if [[ $TARGET == "production" && -n $ZULIP_EMAIL && -n $ZULIP_API_KEY ]]; then

    REPO_BASE_URL="https://github.com/india-ultimate/hub"
    # Commit info
    LAST_COMMIT_SHA=$(git log -1 --pretty=format:"%H")
    LAST_COMMIT_MESSAGE=$(git log -1 --pretty=format:"'%s' by %an")
    COMMIT_URL="$REPO_BASE_URL/commit/$LAST_COMMIT_SHA"

    # Get the name and email of the user from Git config
    GIT_USER_NAME=$(git config user.name)
    GIT_USER_EMAIL=$(git config user.email)

    MESSAGE="Deployment by $GIT_USER_NAME ($GIT_USER_EMAIL)

$LAST_COMMIT_MESSAGE.

[View Commit]($COMMIT_URL)"

    # Send notification to Zulip
    curl -s -X POST "$ZULIP_SITE/api/v1/messages" \
        -u "$ZULIP_EMAIL:$ZULIP_API_KEY" \
        -d "type=stream" \
        -d "to=tech%20backend" \
        -d "subject=Deploys" \
        -d "content=$MESSAGE"
fi
