#!/usr/bin/env bash

set -euo pipefail

GIT_SOURCE=https://github.com/india-ultimate/hub
REF_PATH=refs/heads/main
BASE=$(git ls-remote ${GIT_SOURCE} ${REF_PATH} | awk -F' ' '{print $1}')

git fetch ${GIT_SOURCE} ${REF_PATH} > /dev/null 2>&1

COMMITS=$(git rev-list --count "${BASE}..HEAD")
if [[ "$COMMITS" -gt 0 ]]; then
    gitlint --commits "$BASE..HEAD"
fi
