# Generated by Django 4.2.2 on 2023-06-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="not_in_india",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="player",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")], max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="state_ut",
            field=models.CharField(
                choices=[
                    ("AN", "Andaman and Nicobar Islands"),
                    ("AP", "Andhra Pradesh"),
                    ("AR", "Arunachal Pradesh"),
                    ("AS", "Assam"),
                    ("BR", "Bihar"),
                    ("CDG", "Chandigarh"),
                    ("CG", "Chhattisgarh"),
                    ("DHDD", "Dadra & Nagar Haveli and Daman & Diu"),
                    ("DL", "Delhi"),
                    ("GA", "Goa"),
                    ("GJ", "Gujarat"),
                    ("HR", "Haryana"),
                    ("HP", "Himachal Pradesh"),
                    ("JK", "Jammu and Kashmir"),
                    ("JH", "Jharkhand"),
                    ("KA", "Karnataka"),
                    ("KL", "Kerala"),
                    ("LK", "Ladakh"),
                    ("LD", "Lakshadweep"),
                    ("MP", "Madhya Pradesh"),
                    ("MH", "Maharashtra"),
                    ("MN", "Manipur"),
                    ("ML", "Meghalaya"),
                    ("MZ", "Mizoram"),
                    ("NL", "Nagaland"),
                    ("OR", "Odisha"),
                    ("PY", "Puducherry"),
                    ("PB", "Punjab"),
                    ("RJ", "Rajasthan"),
                    ("SK", "Sikkim"),
                    ("TN", "Tamil Nadu"),
                    ("TL", "Telangana"),
                    ("TR", "Tripura"),
                    ("UP", "Uttar Pradesh"),
                    ("UK", "Uttarakhand"),
                    ("WB", "West Bengal"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="vaccination",
            name="vaccination_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CVSHLD", "Covishield"),
                    ("CVXN", "Covaxin"),
                    ("MDRN", "Moderna"),
                    ("SPTNK", "Sputnik"),
                    ("JNJ", "Johnson & Johnson"),
                ],
                max_length=10,
            ),
        ),
    ]
