# Generated by Django 4.2.2 on 2023-07-15 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0005_guardianship_remove_player_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayTransaction",
            fields=[
                ("order_id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("payment_id", models.CharField(max_length=255)),
                ("payment_signature", models.CharField(max_length=255)),
                ("amount", models.IntegerField()),
                ("currency", models.CharField(max_length=5)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.membership"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
