# Generated by Django 4.2.2 on 2023-07-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0006_razorpaytransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
