# Generated by Django 4.2.2 on 2023-07-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0007_alter_membership_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="razorpaytransaction",
            name="end_date",
            field=models.DateField(default="1900-01-01"),
        ),
        migrations.AddField(
            model_name="razorpaytransaction",
            name="start_date",
            field=models.DateField(default="1900-01-01"),
        ),
    ]
