# Generated by Django 4.2.2 on 2023-07-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0008_razorpaytransaction_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ultimate_central_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="event",
            name="ultimate_central_slug",
            field=models.SlugField(default="unknown"),
        ),
    ]
