# Generated by Django 4.2.2 on 2023-07-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0009_event_ultimate_central_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="occupation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Student", "Student"),
                    ("Business", "Own business"),
                    ("Government", "Government"),
                    ("Non-profit", "NGO / NPO"),
                    ("Other", "Other"),
                    ("Unemployed", "Unemployed"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
