# Generated by Django 4.2.2 on 2023-07-25 04:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0012_alter_guardianship_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_guardian",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_player",
        ),
    ]
