# Generated by Django 4.2.2 on 2023-07-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0013_remove_user_is_guardian_remove_user_is_player"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="razorpaytransaction",
            name="membership",
        ),
        migrations.AddField(
            model_name="razorpaytransaction",
            name="players",
            field=models.ManyToManyField(to="server.player"),
        ),
    ]
