# Generated by Django 4.2.2 on 2023-07-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0015_rename_vaccination_certificate_vaccination_certificate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccination",
            name="other_name",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="vaccination",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CVSHLD", "Covishield"),
                    ("CVXN", "Covaxin"),
                    ("MDRN", "Moderna"),
                    ("SPTNK", "Sputnik"),
                    ("JNJ", "Johnson & Johnson"),
                    ("OTHER", "Other"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
