# Generated by Django 4.2.2 on 2023-08-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0016_membership_waiver_signed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="waiver_valid",
            field=models.BooleanField(default=False),
        ),
    ]
