# Generated by Django 4.2.2 on 2023-08-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0017_membership_waiver_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="ultimate_central_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
