# Generated by Django 4.2.2 on 2023-08-16 03:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0019_team_ucperson_ucregistration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="india_ultimate_profile",
        ),
    ]
