# Generated by Django 4.2.2 on 2023-08-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0020_remove_player_india_ultimate_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="sponsored",
            field=models.BooleanField(default=False),
        ),
    ]
