# Generated by Django 4.2.2 on 2023-08-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0022_alter_player_ultimate_central_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="team_name",
        ),
        migrations.AddField(
            model_name="player",
            name="teams",
            field=models.ManyToManyField(related_name="players", to="server.team"),
        ),
    ]
