# Generated by Django 4.2.2 on 2023-08-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0023_remove_player_team_name_player_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="ultimate_central_slug",
            field=models.SlugField(default="unknown"),
        ),
    ]
