# Generated by Django 4.2.2 on 2023-08-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0025_player_imported_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(default="unknown", max_length=255),
        ),
    ]
