# Generated by Django 4.2.2 on 2023-09-18 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0026_event_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualTransaction",
            fields=[
                (
                    "transaction_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("amount", models.IntegerField()),
                ("currency", models.CharField(max_length=5)),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("validated", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="server.event",
                    ),
                ),
                ("players", models.ManyToManyField(to="server.player")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
