# Generated by Django 4.2.2 on 2023-09-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0028_alter_vaccination_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualtransaction",
            name="validation_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
