# Generated by Django 4.2.2 on 2023-09-22 05:08

from django.db import migrations, models

import server.models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0029_manualtransaction_validation_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaccination",
            name="certificate",
            field=models.FileField(
                blank=True, max_length=256, upload_to=server.models.upload_vaccination_certificates
            ),
        ),
    ]
