# Generated by Django 4.2.2 on 2023-09-28 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0030_alter_vaccination_certificate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accreditation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_valid", models.BooleanField()),
                (
                    "level",
                    models.CharField(
                        choices=[("STD", "Standard"), ("ADV", "Advanced")], max_length=10
                    ),
                ),
                ("date", models.DateField()),
                (
                    "certificate",
                    models.FileField(max_length=256, upload_to="accreditation_certificates/"),
                ),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="server.player"
                    ),
                ),
            ],
        ),
    ]
