# Generated by Django 4.2.2 on 2023-10-03 11:13

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def code(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Player = apps.get_model("server", "Player")  # noqa: N806
    Player.objects.filter(gender="M").update(match_up="M")
    Player.objects.filter(gender="F").update(match_up="F")
    male_matching_ids = [2505]
    Player.objects.filter(id__in=male_matching_ids).update(match_up="M")
    female_matching_ids = [3026, 2096]
    Player.objects.filter(id__in=female_matching_ids).update(match_up="F")


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0031_accreditation"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="match_up",
            field=models.CharField(max_length=30, default="M", null=True),
        ),
        migrations.RunPython(code=code),
        migrations.AlterField(
            model_name="player",
            name="match_up",
            field=models.CharField(max_length=30),
        ),
    ]
