# Generated by Django 4.2.2 on 2023-10-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0032_player_match_up"),
    ]

    operations = [
        migrations.AddField(
            model_name="accreditation",
            name="wfdf_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
