# Generated by Django 4.2.2 on 2023-10-06 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0036_match_video_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpiritScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rules", models.PositiveIntegerField()),
                ("fouls", models.PositiveIntegerField()),
                ("fair", models.PositiveIntegerField()),
                ("positive", models.PositiveIntegerField()),
                ("communication", models.PositiveIntegerField()),
                (
                    "msp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="msp",
                        to="server.ucperson",
                    ),
                ),
                (
                    "mvp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mvp",
                        to="server.ucperson",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="spirit_score_team_1",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spirit_score_team_1",
                to="server.spiritscore",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="spirit_score_team_2",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spirit_score_team_2",
                to="server.spiritscore",
            ),
        ),
    ]
