# Generated by Django 4.2.2 on 2023-10-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0037_spiritscore_match_spirit_score_team_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="spirit_ranking",
            field=models.JSONField(default=list),
        ),
    ]
