# Generated by Django 4.2.2 on 2023-10-17 15:55

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from server.tournament.utils import rank_spirit_scores


def code(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Add a 'rank' field and sort by ranks."""
    Tournament = apps.get_model("server", "Tournament")  # noqa: N806
    for tournament in Tournament.objects.all():
        tournament.spirit_ranking = rank_spirit_scores(tournament.spirit_ranking)
        tournament.save(update_fields=["spirit_ranking"])


def reverse_code(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Remove the 'rank' field and sort by points."""
    Tournament = apps.get_model("server", "Tournament")  # noqa: N806
    for tournament in Tournament.objects.all():
        for ranking in tournament.spirit_ranking:
            ranking.pop("rank")
        tournament.spirit_ranking = sorted(
            tournament.spirit_ranking, key=lambda x: x["points"], reverse=True
        )
        tournament.save(update_fields=["spirit_ranking"])


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0038_tournament_spirit_ranking"),
    ]

    operations = [
        migrations.RunPython(code=code, reverse_code=reverse_code),
    ]
