# Generated by Django 4.2.2 on 2023-10-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0039_tournament_spirit_rankings_rank_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="match_up",
            field=models.CharField(
                choices=[("M", "Male matching"), ("F", "Female matching")], max_length=30
            ),
        ),
    ]
