# Generated by Django 4.2.2 on 2023-10-21 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0040_alter_player_match_up"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhonePeTransaction",
            fields=[
                ("transaction_id", models.UUIDField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField()),
                ("currency", models.CharField(max_length=5)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField(default="1900-01-01")),
                ("end_date", models.DateField(default="1900-01-01")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("error", "Error"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="server.event",
                    ),
                ),
                ("players", models.ManyToManyField(to="server.player")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
