# Generated by Django 4.2.2 on 2023-11-08 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0041_phonepetransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("score_team_1", models.PositiveIntegerField(default=0)),
                ("score_team_2", models.PositiveIntegerField(default=0)),
                (
                    "entered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.player"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="suggested_score_team_1",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggested_score_team_1",
                to="server.matchscore",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="suggested_score_team_2",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggested_score_team_2",
                to="server.matchscore",
            ),
        ),
    ]
