# Generated by Django 4.2.2 on 2023-11-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0042_matchscore_match_suggested_score_team_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="ultimate_central_slug",
            field=models.SlugField(default="unknown", max_length=200),
        ),
    ]
