# Generated by Django 4.2.2 on 2023-11-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0043_alter_event_ultimate_central_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="self_spirit_score_team_1",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="self_spirit_score_team_1",
                to="server.spiritscore",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="self_spirit_score_team_2",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="self_spirit_score_team_2",
                to="server.spiritscore",
            ),
        ),
    ]
