# Generated by Django 4.2.2 on 2023-11-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0044_match_self_spirit_score_team_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spiritscore",
            name="comments",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
