# Generated by Django 4.2.2 on 2023-10-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0045_spiritscore_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
