# Generated by Django 4.2.2 on 2023-12-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0047_tournament_match_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="rules",
            field=models.TextField(blank=True, null=True),
        ),
    ]
