# Generated by Django 4.2.2 on 2023-12-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0048_tournament_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="spiritscore",
            name="total",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
