# Generated by Django 4.2.2 on 2023-12-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0050_alter_spiritscore_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_tournament_admin",
            field=models.BooleanField(default=False),
        ),
    ]
