# Generated by Django 4.2.2 on 2024-01-24 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0052_match_duration_mins"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentaryInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("jersey_number", models.PositiveIntegerField()),
                ("ultimate_origin", models.TextField()),
                ("ultimate_attraction", models.TextField()),
                ("ultimate_fav_role", models.TextField()),
                ("ultimate_fav_exp", models.TextField()),
                ("interests", models.TextField()),
                ("fun_fact", models.TextField()),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentary_info",
                        to="server.player",
                    ),
                ),
            ],
        ),
    ]
