# Generated by Django 4.2.2 on 2024-01-24 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0053_commentaryinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("is_broadcasted", models.BooleanField(default=False)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.tournament"
                    ),
                ),
            ],
            options={
                "unique_together": {("tournament", "name")},
            },
        ),
        migrations.AddField(
            model_name="match",
            name="field_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="server.tournamentfield",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="match",
            unique_together={("tournament", "time", "field_reference")},
        ),
    ]
