# Generated by Django 4.2.2 on 2024-03-18 15:30

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0057_tournamentfield_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="occupation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Student", "Student"),
                    ("College-Student", "College Student"),
                    ("Business", "Own business"),
                    ("Government", "Government"),
                    ("Non-profit", "NGO / NPO"),
                    ("Other", "Other"),
                    ("Unemployed", "Unemployed"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CollegeId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("expiry", models.DateField()),
                ("card_front", models.FileField(max_length=256, upload_to="college_ids/")),
                ("card_back", models.FileField(max_length=256, upload_to="college_ids/")),
                ("ocr_name", models.PositiveIntegerField(blank=True, null=True)),
                ("ocr_college", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="college_id",
                        to="server.player",
                    ),
                ),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin("college_id"), models.Model),
        ),
    ]
