# Generated by Django 4.2.2 on 2024-07-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0058_alter_player_occupation_collegeid"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registration_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[("MXD", "Mixed"), ("OPN", "Opens"), ("WMN", "Womens")],
                default="MXD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                choices=[
                    ("DFT", "Draft"),
                    ("REG", "Registering"),
                    ("SCH", "Scheduling"),
                    ("LIV", "Live"),
                    ("COM", "Completed"),
                ],
                default="DFT",
                max_length=3,
            ),
        ),
    ]
