# Generated by Django 4.2.2 on 2024-07-02 04:15

from django.db import migrations, models

import server.models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0060_team_state_ut"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Club", "Club"),
                    ("College", "College"),
                    ("State", "State"),
                    ("National", "National"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="city",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="image",
            field=models.FileField(
                blank=True, max_length=256, upload_to=server.models.upload_team_logos
            ),
        ),
    ]
