# Generated by Django 4.2.2 on 2024-07-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0061_team_category_team_city_team_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
