# Generated by Django 4.2.2 on 2024-07-08 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0068_event_copy_uc_slug_field"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together={("event", "player")},
        ),
    ]
