# Generated by Django 4.2.2 on 2024-07-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0071_team_registration_non_nullable_rename_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="player_registration_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="player_registration_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
