# Generated by Django 4.2.2 on 2024-07-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0072_alter_tournament_use_uc_registrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentfield",
            name="location_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
