# Generated by Django 4.2.2 on 2024-08-07 07:12

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models

from server.utils import default_invitation_expiry_date


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0079_spiritscore_msp_v2_spiritscore_mvp_v2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("name", models.CharField(max_length=255)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin("season"), models.Model),
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("MXD", "Mixed"), ("OPN", "Opens"), ("WMN", "Womens")],
                        max_length=3,
                    ),
                ),
                (
                    "catgory",
                    models.CharField(
                        choices=[
                            ("Club", "Club"),
                            ("College", "College"),
                            ("School", "School"),
                            ("State", "State"),
                        ],
                        max_length=7,
                    ),
                ),
                ("series_roster_max_players", models.PositiveSmallIntegerField()),
                ("event_min_players_male", models.PositiveSmallIntegerField()),
                ("event_min_players_female", models.PositiveSmallIntegerField()),
                ("event_max_players_male", models.PositiveSmallIntegerField()),
                ("event_max_players_female", models.PositiveSmallIntegerField()),
                ("player_transfer_window_start_date", models.DateField(blank=True, null=True)),
                ("player_transfer_window_end_date", models.DateField(blank=True, null=True)),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="server.season",
                    ),
                ),
                ("teams", models.ManyToManyField(related_name="series", to="server.team")),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin("series"), models.Model),
        ),
        migrations.AddField(
            model_name="event",
            name="max_num_teams",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SeriesRosterInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Declined", "Declined"),
                            ("Expired", "Expired"),
                        ],
                        default="Pending",
                        max_length=8,
                    ),
                ),
                (
                    "expires_on",
                    models.DateField(default=default_invitation_expiry_date),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series_invitations_sent",
                        to="server.user",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.series"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.team"
                    ),
                ),
                (
                    "to_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series_invitations_received",
                        to="server.player",
                    ),
                ),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("series_roster_invitation"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="SeriesRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.player"
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.series"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.team"
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "player")},
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("series_registration"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="EventRosterInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Declined", "Declined"),
                            ("Expired", "Expired"),
                        ],
                        default="Pending",
                        max_length=8,
                    ),
                ),
                (
                    "expires_on",
                    models.DateField(default=default_invitation_expiry_date),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.event"
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_invitations_sent",
                        to="server.user",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.team"
                    ),
                ),
                (
                    "to_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_invitations_received",
                        to="server.player",
                    ),
                ),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("event_roster_invitation"),
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="server.series",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="series_registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="server.seriesregistration",
            ),
        ),
    ]
