# Generated by Django 4.2.2 on 2024-08-12 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0080_season_series_event_max_num_teams_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="server.season",
            ),
        ),
    ]
