# Generated by Django 4.2.2 on 2024-08-12 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0081_membership_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="razorpaytransaction",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="server.season",
            ),
        ),
    ]
