# Generated by Django 4.2.2 on 2024-08-16 03:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0083_season_annual_membership_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="volunteers",
            field=models.ManyToManyField(
                related_name="tournament_volunteer", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
