# Generated by Django 4.2.2 on 2024-08-16 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0084_tournament_volunteers"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("FH", "First Half"), ("SH", "Second Half"), ("COM", "Completed")],
                        default="FH",
                        max_length=3,
                    ),
                ),
                ("score_team_1", models.PositiveIntegerField(default=0)),
                ("score_team_2", models.PositiveIntegerField(default=0)),
                (
                    "status_team_1",
                    models.CharField(
                        choices=[
                            ("PLS", "Pending Line Selection"),
                            ("CLS", "Completed Line Selection"),
                        ],
                        default="PLS",
                        max_length=3,
                    ),
                ),
                (
                    "status_team_2",
                    models.CharField(
                        choices=[
                            ("PLS", "Pending Line Selection"),
                            ("CLS", "Completed Line Selection"),
                        ],
                        default="PLS",
                        max_length=3,
                    ),
                ),
                (
                    "current_possession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_possession",
                        to="server.team",
                    ),
                ),
                (
                    "initial_possession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initial_possession",
                        to="server.team",
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="server.match",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_stats",
                        to="server.tournament",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "started_on",
                    models.CharField(choices=[("OF", "Offense"), ("DE", "Defense")], max_length=3),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LS", "Line Selected"),
                            ("SC", "Score"),
                            ("DR", "Drop"),
                            ("TA", "Throwaway"),
                            ("BL", "Block"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "assisted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_events_assisted",
                        to="server.player",
                    ),
                ),
                (
                    "block_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_events_blocks",
                        to="server.player",
                    ),
                ),
                (
                    "drop_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_events_drops",
                        to="server.player",
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(related_name="match_events_played", to="server.player"),
                ),
                (
                    "scored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_events_scored",
                        to="server.player",
                    ),
                ),
                (
                    "stats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="server.matchstats",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_events",
                        to="server.team",
                    ),
                ),
                (
                    "throwaway_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_events_throwaways",
                        to="server.player",
                    ),
                ),
            ],
        ),
    ]
