# Generated by Django 4.2.2 on 2024-08-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0085_matchstats_matchevent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="series",
            old_name="catgory",
            new_name="category",
        ),
        migrations.AddField(
            model_name="seriesrosterinvitation",
            name="rsvp_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="category",
            field=models.CharField(
                choices=[
                    ("Club", "Club"),
                    ("College", "College"),
                    ("School", "School"),
                    ("State", "State"),
                    ("National", "National"),
                ],
                default="Club",
                max_length=25,
            ),
        ),
    ]
