# Generated by Django 4.2.2 on 2024-08-16 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0086_rename_catgory_series_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="series",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="series",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="series",
                to="server.season",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="series",
            unique_together={("season", "name")},
        ),
    ]
