# Generated by Django 4.2.2 on 2024-08-22 13:14


import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0087_series_slug_alter_series_name_alter_series_season_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seriesrosterinvitation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="seriesrosterinvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Declined", "Declined"),
                    ("Expired", "Expired"),
                    ("Revoked", "Revoked"),
                ],
                default="Pending",
                max_length=8,
            ),
        ),
    ]
