# Generated by Django 4.2.2 on 2024-08-23 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0088_seriesrosterinvitation_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="teams",
            field=models.ManyToManyField(blank=True, related_name="series", to="server.team"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="teams",
            field=models.ManyToManyField(blank=True, related_name="tournaments", to="server.team"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="volunteers",
            field=models.ManyToManyField(
                blank=True, related_name="tournament_volunteer", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
