# Generated by Django 4.2.2 on 2024-08-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0089_alter_series_teams_alter_tournament_teams_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="teams",
            field=models.ManyToManyField(blank=True, related_name="players", to="server.team"),
        ),
    ]
