# Generated by Django 4.2.2 on 2024-09-11 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0090_alter_player_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="razorpaytransaction",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="server.team",
            ),
        ),
        migrations.AddField(
            model_name="razorpaytransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("annual-membership", "Annual Membership"),
                    ("team-reg", "Team Registration"),
                    ("player-reg", "Player Registration"),
                ],
                default="annual-membership",
                max_length=30,
            ),
        ),
    ]
