# Generated by Django 4.2.2 on 2024-09-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0091_razorpaytransaction_team_razorpaytransaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="player_fee",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="team_fee",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
