# Generated by Django 4.2.2 on 2024-10-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0093_alter_tournament_current_seeding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_membership_needed",
            field=models.BooleanField(default=False),
        ),
    ]
