# Generated by Django 4.2.2 on 2024-10-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0096_event_partial_team_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="razorpaytransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("annual-membership", "Annual Membership"),
                    ("team-reg", "Team Registration"),
                    ("partial-team-reg", "Partial Team Registration"),
                    ("player-reg", "Player Registration"),
                ],
                default="annual-membership",
                max_length=30,
            ),
        ),
    ]
