# Generated by Django 4.2.2 on 2024-11-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0097_alter_razorpaytransaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchstats",
            name="current_ratio",
            field=models.CharField(
                choices=[("FEMALE", "Female"), ("MALE", "Male"), ("NA", "NA")],
                default="NA",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="matchstats",
            name="initial_ratio",
            field=models.CharField(
                choices=[("FEMALE", "Female"), ("MALE", "Male"), ("NA", "NA")],
                default="NA",
                max_length=10,
            ),
        ),
    ]
