# Generated by Django 4.2.2 on 2024-12-16 15:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0098_matchstats_current_ratio_matchstats_initial_ratio"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="seriesregistration",
            unique_together=set(),
        ),
    ]
