# Generated by Django 4.2.2 on 2024-12-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0099_alter_seriesregistration_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="event_max_players_total",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="series",
            name="event_min_players_total",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
