# Generated by Django 4.2.2 on 2025-01-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0100_series_event_max_players_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="points",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
