# Generated by Django 4.2.2 on 2025-05-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0103_ticket_ticketmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchevent",
            name="players",
            field=models.ManyToManyField(
                blank=True, related_name="match_events_played", to="server.player"
            ),
        ),
    ]
