# Generated by Django 4.2.2 on 2025-05-30 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0105_election_rankedvote_candidate_voterverification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("round_number", models.IntegerField()),
                ("votes", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("eliminated", "Eliminated"),
                            ("winner", "Winner"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.candidate"
                    ),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="server.election",
                    ),
                ),
            ],
            options={
                "ordering": ["round_number", "-votes"],
                "unique_together": {("election", "candidate", "round_number")},
            },
        ),
    ]
