# Generated by Django 4.2.2 on 2025-05-30 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0106_electionresult"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="position",
        ),
    ]
