# Generated by Django 4.2.2 on 2025-06-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0108_chatsession_chatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="type",
            field=models.CharField(
                choices=[("USER", "User"), ("ASSISTANT", "Assistant")], max_length=10
            ),
        ),
    ]
