# Generated by Django 4.2.2 on 2025-06-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0109_alter_chatmessage_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketmessage",
            name="attachment",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
