# Generated by Django 4.2.2 on 2025-07-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0110_alter_ticketmessage_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="profile_pic_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
