# Generated by Django 4.2.2 on 2025-07-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0111_player_profile_pic_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="manifesto_link",
            field=models.URLField(
                blank=True, help_text="External link to candidate's manifesto", null=True
            ),
        ),
    ]
