# Generated by Django 4.2.2 on 2025-09-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0112_candidate_manifesto_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="supporter_annual_membership_amount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
