# Generated by Django 4.2.2 on 2025-09-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0114_servicerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="service_players",
            field=models.ManyToManyField(
                blank=True, related_name="service_requests", to="server.player"
            ),
        ),
    ]
