# Generated by Django 4.2.2 on 2025-09-29 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0115_servicerequest_service_players"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_members_only", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                ("action_text", models.CharField(blank=True, max_length=100, null=True)),
                ("action_url", models.URLField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="server_anno_slug_757b70_idx"),
                    models.Index(fields=["created_at"], name="server_anno_created_3284a1_idx"),
                ],
            },
        ),
    ]
