# Generated by Django 4.2.2 on 2025-09-30 13:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0116_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="type",
            field=models.CharField(
                choices=[
                    ("competitions", "Competitions"),
                    ("executive_board", "Executive Board"),
                    ("project_gamechangers", "Project GameChangers"),
                    ("finance", "Finance"),
                ],
                default="competitions",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
