# Generated by Django 4.2.2 on 2025-09-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0117_announcement_type_alter_announcement_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("type", models.CharField(choices=[("SEND_EMAIL", "Send Email")], max_length=50)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("completed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("failed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["started_at", "completed_at", "failed_at"],
                        name="server_task_started_b4b426_idx",
                    )
                ],
            },
        ),
    ]
