# Generated by Django 4.2.2 on 2025-10-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0118_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="type",
            field=models.CharField(
                choices=[
                    ("competitions", "Competitions"),
                    ("executive_board", "Executive Board"),
                    ("project_gamechangers", "Project GameChangers"),
                    ("finance", "Finance"),
                    ("ntc", "NTC"),
                    ("governance", "Governance"),
                    ("safeguarding", "Safeguarding"),
                    ("college", "College"),
                    ("development", "Development"),
                    ("operations", "Operations"),
                ],
                default="competitions",
                max_length=20,
            ),
        ),
    ]
