# Generated by Django 4.2.2 on 2025-12-29 05:21

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0119_alter_announcement_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerWrapped",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="The year for which this wrapped data is generated"
                    ),
                ),
                (
                    "tournaments_played",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of tournaments played in this year"
                    ),
                ),
                (
                    "total_games",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of games played in this year"
                    ),
                ),
                (
                    "total_scores",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of scores in this year"
                    ),
                ),
                (
                    "total_assists",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of assists in this year"
                    ),
                ),
                (
                    "total_blocks",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of blocks in this year"
                    ),
                ),
                (
                    "match_mvps",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of Match MVP awards received"
                    ),
                ),
                (
                    "match_msps",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of Match MSP awards received"
                    ),
                ),
                (
                    "continuous_streak_scored_or_assisted",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Longest continuous streak of games where player either scored or assisted",
                    ),
                ),
                (
                    "most_scores_in_tournament",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Tournament with most scores: {tournament_name, tournament_id, count}",
                    ),
                ),
                (
                    "most_assists_in_tournament",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Tournament with most assists: {tournament_name, tournament_id, count}",
                    ),
                ),
                (
                    "most_blocks_in_tournament",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Tournament with most blocks: {tournament_name, tournament_id, count}",
                    ),
                ),
                (
                    "teams_played_for",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of teams played for with tournament counts: [{team_name, team_id, tournament_count}, ...]",
                    ),
                ),
                (
                    "top_teammates_i_assisted",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Top 5 teammates I assisted: [{player_name, player_id, count}, ...]",
                    ),
                ),
                (
                    "top_teammates_who_assisted_me",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Top 5 teammates who assisted me: [{player_name, player_id, count}, ...]",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrapped_data",
                        to="server.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "player"],
                "indexes": [
                    models.Index(fields=["player", "year"], name="server_play_player__fad375_idx"),
                    models.Index(fields=["year"], name="server_play_year_6e9348_idx"),
                ],
                "unique_together": {("player", "year")},
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("player_wrapped"),
                models.Model,
            ),
        ),
    ]
