# Generated by Django 4.2.2 on 2025-12-31 13:29

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def backfill_event_scores(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    match_event = apps.get_model("server", "MatchEvent")
    match_stats = apps.get_model("server", "MatchStats")

    for stats in match_stats.objects.select_related("match"):
        match = stats.match
        score_team_1 = 0
        score_team_2 = 0

        for event in match_event.objects.filter(stats=stats).order_by("time"):
            if event.type == "SC":
                if event.team_id == match.team_1_id:
                    score_team_1 += 1
                elif event.team_id == match.team_2_id:
                    score_team_2 += 1

            event.post_event_score_team_1 = score_team_1
            event.post_event_score_team_2 = score_team_2
            event.save(update_fields=["post_event_score_team_1", "post_event_score_team_2"])


def reverse_backfill(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    match_event = apps.get_model("server", "MatchEvent")
    match_event.objects.all().update(post_event_score_team_1=None, post_event_score_team_2=None)


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0120_playerwrapped"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchevent",
            name="post_event_score_team_1",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matchevent",
            name="post_event_score_team_2",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_event_scores, reverse_backfill),
    ]
