# Generated by Django 4.2.2 on 2025-12-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0120_playerwrapped"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchevent",
            name="post_event_score_team_1",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matchevent",
            name="post_event_score_team_2",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
