# Generated by Django 4.2.2 on 2026-01-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0121_matchevent_post_event_score_team_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="forum_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
