# Generated by Django 4.2.2 on 2026-01-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0122_user_forum_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="forum_discussion_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
