# Generated by Django 4.2.2 on 2026-02-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0124_create_flarum_discussions_for_existing_announcements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Account", "Account"),
                    ("Competitions", "Competitions"),
                    ("Membership", "Membership"),
                    ("Tournament", "Tournament"),
                    ("Payment", "Payment"),
                    ("Tech", "Tech"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=100,
                null=True,
            ),
        ),
    ]
