# Generated by Django 4.2.2 on 2026-02-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0127_remove_ticket_closed_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[("OPN", "Open"), ("PRG", "In Progress"), ("RES", "Resolved")],
                default="OPN",
                max_length=3,
            ),
        ),
    ]
