# Generated by Django 4.2.2 on 2026-01-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0128_alter_ticket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="player_late_penalty",
            field=models.PositiveIntegerField(
                default=0, help_text="Per-day late registration penalty for players, in paise."
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="player_late_penalty_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="team_late_penalty",
            field=models.PositiveIntegerField(
                default=0, help_text="Per-day late registration penalty for teams, in paise."
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="team_late_penalty_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="team_partial_registration_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="partial_team_fee",
            field=models.PositiveIntegerField(
                default=0, help_text="Partial team registration fee in paise."
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="player_fee",
            field=models.PositiveIntegerField(
                default=0, help_text="Player registration fee in paise."
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="team_fee",
            field=models.PositiveIntegerField(
                default=0, help_text="Team registration fee in paise."
            ),
        ),
    ]
