# Generated by Django 4.2.2 on 2026-01-27


from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def backfill_late_penalty_end_dates(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """
    Backfill late penalty end dates and partial registration end date
    to match their corresponding registration end dates for existing events.
    """
    event_model = apps.get_model("server", "Event")

    # Backfill team_late_penalty_end_date from team_registration_end_date
    for event in event_model.objects.filter(
        team_late_penalty_end_date__isnull=True,
        team_registration_end_date__isnull=False,
    ):
        event.team_late_penalty_end_date = event.team_registration_end_date
        event.save(update_fields=["team_late_penalty_end_date"])

    # Backfill player_late_penalty_end_date from player_registration_end_date
    for event in event_model.objects.filter(
        player_late_penalty_end_date__isnull=True,
        player_registration_end_date__isnull=False,
    ):
        event.player_late_penalty_end_date = event.player_registration_end_date
        event.save(update_fields=["player_late_penalty_end_date"])

    # Backfill team_partial_registration_end_date from team_registration_end_date
    for event in event_model.objects.filter(
        team_partial_registration_end_date__isnull=True,
        team_registration_start_date__isnull=False,
    ):
        event.team_partial_registration_end_date = event.team_registration_start_date
        event.save(update_fields=["team_partial_registration_end_date"])


def reverse_backfill(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """
    Reverse migration: Set the fields back to null.
    """
    event_model = apps.get_model("server", "Event")
    event_model.objects.update(
        team_late_penalty_end_date=None,
        player_late_penalty_end_date=None,
        team_partial_registration_end_date=None,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0129_event_player_late_penalty_and_more"),
    ]

    operations = [
        migrations.RunPython(
            backfill_late_penalty_end_dates,
            reverse_backfill,
        ),
    ]
