# Generated by Django 4.2.2 on 2026-02-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0131_remove_tournament_registering_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                choices=[
                    ("DFT", "Draft"),
                    ("SCH", "Scheduling"),
                    ("LIV", "Live"),
                    ("COM", "Completed"),
                ],
                default="DFT",
                max_length=3,
            ),
        ),
    ]
