# Generated by Django 4.2.2 on 2026-03-02 21:47

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0132_alter_tournament_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwissRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("num_rounds", models.PositiveIntegerField()),
                ("current_round", models.PositiveIntegerField(default=0)),
                ("initial_seeding", models.JSONField()),
                ("results", models.JSONField()),
                (
                    "tournament",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="server.tournament"
                    ),
                ),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("swiss_round"),
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="swiss_round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="server.swissround",
            ),
        ),
    ]
