# Generated by Django 4.2.2 on 2026-03-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0133_swissround_match_swiss_round"),
    ]

    operations = [
        migrations.AddField(
            model_name="swissround",
            name="byes",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
