# Generated by Django 4.2.2 on 2026-03-05 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0134_swiss_round_byes"),
    ]

    operations = [
        migrations.AddField(
            model_name="swissround",
            name="name",
            field=models.CharField(default="A", max_length=2),
        ),
        migrations.AddField(
            model_name="swissround",
            name="sequence_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="swissround",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="server.tournament"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="swissround",
            unique_together={("name", "tournament")},
        ),
    ]
