# Generated by Django 4.2.2 on 2026-06-08 15:24

import django.db.models.deletion
import django_prometheus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0136_swissround_round_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("fields", models.JSONField(default=list)),
                ("payment_amount", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin("form"), models.Model),
        ),
        migrations.AlterField(
            model_name="razorpaytransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("annual-membership", "Annual Membership"),
                    ("team-reg", "Team Registration"),
                    ("partial-team-reg", "Partial Team Registration"),
                    ("player-reg", "Player Registration"),
                    ("form-payment", "Form Payment"),
                ],
                default="annual-membership",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="FormResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("answers", models.JSONField(default=dict)),
                ("is_paid", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="server.form",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="server.razorpaytransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("form_response"),
                models.Model,
            ),
        ),
    ]
