# Generated by Django 4.2.2 on 2026-08-20 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0138_backfill_tournament_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="directors",
            field=models.ManyToManyField(
                blank=True, related_name="directed_tournaments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
