# Generated by Django 4.2.2 on 2026-08-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0140_tournament_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentagentsession",
            name="history_cleared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
