# Generated by Django 4.2.2 on 2026-08-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0140_tournament_directors"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentproposal",
            name="last_error",
            field=models.TextField(blank=True, default=""),
        ),
    ]
