# Generated by Django 4.2.2 on 2026-08-19 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0141_agentproposal_last_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phase", models.CharField(blank=True, default="", max_length=32)),
                ("model_id", models.CharField(blank=True, default="", max_length=64)),
                ("rounds", models.PositiveSmallIntegerField(default=0)),
                ("tokens_in", models.PositiveIntegerField(default=0)),
                ("tokens_out", models.PositiveIntegerField(default=0)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("tool_names", models.JSONField(blank=True, default=list)),
                ("proposal_ids", models.JSONField(blank=True, default=list)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("replied", "Replied"),
                            ("asked", "Asked a question"),
                            ("error", "Error"),
                        ],
                        default="replied",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="server.tournamentagentsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "created_at"], name="server_agen_session_cc63a2_idx"
                    )
                ],
            },
        ),
    ]
