# Generated by Django 4.2.2 on 2026-09-24 05:21

import secrets

import django.db.models.deletion
import django_prometheus.models
from django.conf import settings
from django.db import migrations, models

import server.duplicates.models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0142_align_usernames"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountMerge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("duplicate_user_ids", models.JSONField(default=list)),
                ("duplicate_emails", models.JSONField(default=list)),
                ("matched_by", models.CharField(blank=True, max_length=100)),
                ("plan", models.JSONField(default=dict)),
                ("record", models.JSONField(default=dict)),
                ("snapshot", models.JSONField(default=list)),
                ("primary_id", models.IntegerField(blank=True, null=True)),
                ("primary_email", models.CharField(blank=True, max_length=254)),
                ("actor_id", models.IntegerField(blank=True, null=True)),
                ("actor_email", models.CharField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("account_merge"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ClusterMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "claim_token",
                    models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True),
                ),
                (
                    "expires_at",
                    models.DateTimeField(default=server.duplicates.models.default_claim_expiry),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("account_id", models.IntegerField(blank=True, null=True)),
                ("account_email", models.CharField(blank=True, max_length=254)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Not confirmed yet"),
                            ("verified", "Confirmed"),
                            ("pending-staff", "Waiting for our team"),
                            ("rejected", "Our team couldn't confirm this one"),
                            ("merged", "Merged"),
                            ("merged-elsewhere", "Merged into a different account"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("verified_by_id", models.IntegerField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "proof",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email-code", "A code sent to it"),
                            ("same-inbox", "The same inbox as the keeper"),
                            ("staff", "Approved by our team"),
                        ],
                        max_length=20,
                    ),
                ),
                ("merged_into_id", models.IntegerField(blank=True, null=True)),
                ("code_hash", models.CharField(blank=True, max_length=64)),
                ("code_for_id", models.IntegerField(blank=True, null=True)),
                ("code_expires_at", models.DateTimeField(blank=True, null=True)),
                ("code_attempts", models.PositiveSmallIntegerField(default=0)),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("cluster_member"),
                models.Model,
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="type",
            field=models.CharField(
                choices=[
                    ("REQUEST_SPONSORED_MEMBERSHIP", "Request Sponsored Membership"),
                    ("REQUEST_ACCOUNT_MERGE", "Merge accounts"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="EmailAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.CharField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_aliases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("email_alias"),
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="DuplicateCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Detected", "Detected"),
                            ("Notified", "Notified"),
                            ("Resolved", "Resolved"),
                            ("Dismissed", "Dismissed"),
                        ],
                        default="Detected",
                        max_length=10,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("detected", "Found by detection"),
                            ("requested", "Asked for by the keeper"),
                        ],
                        default="detected",
                        max_length=10,
                    ),
                ),
                ("requested_by_id", models.IntegerField(blank=True, null=True)),
                ("matched_by", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dismissed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="server.clustermember",
                    ),
                ),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("duplicate_cluster"),
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="clustermember",
            name="cluster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="server.duplicatecluster",
            ),
        ),
        migrations.AddField(
            model_name="clustermember",
            name="merge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="server.accountmerge",
            ),
        ),
        migrations.AddField(
            model_name="clustermember",
            name="staff_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="server.servicerequest",
            ),
        ),
        migrations.AddField(
            model_name="clustermember",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicate_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ClusterEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("detected", "Detected"),
                            ("requested", "Requested"),
                            ("emailed", "Emailed"),
                            ("code-sent", "Code Sent"),
                            ("code-verified", "Code Verified"),
                            ("code-failed", "Code Failed"),
                            ("code-locked", "Code Locked"),
                            ("staff-requested", "Staff Requested"),
                            ("staff-approved", "Staff Approved"),
                            ("staff-rejected", "Staff Rejected"),
                            ("merged", "Merged"),
                            ("merged-elsewhere", "Merged Elsewhere"),
                            ("keeper-moved", "Keeper Moved"),
                            ("account-deleted", "Account Deleted"),
                            ("dismissed", "Dismissed"),
                            ("cancelled", "Cancelled"),
                            ("closed", "Closed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actor_id", models.IntegerField(blank=True, null=True)),
                ("actor_email", models.CharField(blank=True, max_length=254)),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="server.duplicatecluster",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="server.clustermember",
                    ),
                ),
            ],
            options={
                "ordering": ["at", "id"],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("cluster_event"),
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="accountmerge",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merges",
                to="server.duplicatecluster",
            ),
        ),
        migrations.AddField(
            model_name="accountmerge",
            name="merged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merges_performed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accountmerge",
            name="primary_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="account_merges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clustermember",
            unique_together={("cluster", "user")},
        ),
    ]
