# Generated by Django 4.2.2 on 2026-09-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0151_backfill_grants"),
    ]

    operations = [
        migrations.AddField(
            model_name="seriesregistration",
            name="role",
            field=models.CharField(
                choices=[
                    ("DFLT", "Default"),
                    ("CAP", "Captain"),
                    ("SCAP", "Spirit Captain"),
                    ("COACH", "Coach"),
                    ("ACOACH", "Assistant Coach"),
                    ("MNGR", "Manager"),
                ],
                default="DFLT",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="seriesrosterinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("DFLT", "Default"),
                    ("CAP", "Captain"),
                    ("SCAP", "Spirit Captain"),
                    ("COACH", "Coach"),
                    ("ACOACH", "Assistant Coach"),
                    ("MNGR", "Manager"),
                ],
                default="DFLT",
                max_length=6,
            ),
        ),
    ]
