# Generated by Django 4.2.2 on 2026-09-26 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0154_order_lines"),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.PositiveIntegerField(help_text="In paise.")),
                (
                    "razorpay_refund_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="requested",
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("hub", "Hub"), ("razorpay_dashboard", "Razorpay dashboard")],
                        default="hub",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="server.razorpaytransactionplayer",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="server.razorpaytransaction",
                    ),
                ),
            ],
        ),
    ]
