# Generated by Django 4.2.2 on 2026-09-28 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0157_tier_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("series", models.CharField(max_length=4)),
                ("financial_year", models.CharField(max_length=7)),
                ("last", models.PositiveIntegerField(default=0)),
            ],
            options={
                "unique_together": {("series", "financial_year")},
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("receipt", "Receipt"), ("refund", "Refund note")], max_length=8
                    ),
                ),
                ("number", models.CharField(max_length=16, unique=True)),
                ("financial_year", models.CharField(max_length=7)),
                ("sequence", models.PositiveIntegerField()),
                ("issued_at", models.DateTimeField()),
                ("payer_name", models.CharField(max_length=301)),
                ("payer_email", models.CharField(blank=True, max_length=254)),
                ("payer_phone", models.CharField(blank=True, max_length=20)),
                ("lines", models.JSONField()),
                ("total", models.PositiveIntegerField(help_text="In paise.")),
                (
                    "reference",
                    models.CharField(
                        blank=True, help_text="Razorpay payment or refund ID.", max_length=255
                    ),
                ),
                ("order_id", models.CharField(max_length=255)),
                (
                    "original",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_notes",
                        to="server.receipt",
                    ),
                ),
                (
                    "refund",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="note",
                        to="server.razorpayrefund",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="server.razorpaytransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="receipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "receipt")),
                fields=("transaction",),
                name="one_receipt_per_order",
            ),
        ),
    ]
