# Generated by Django 4.2.2 on 2026-09-29 04:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0159_backfill_receipts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="forum_discussion_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="forum_id",
        ),
    ]
