# Generated by Django 4.2.2 on 2026-09-30 01:09

from typing import Any

from django.db import migrations, models


def keep_default_in_database(apps: Any, schema_editor: Any) -> None:
    # Django sets the default only while adding the column, then drops it. An
    # image from before this migration never sends is_private, so without a
    # default of the database's own, a rollback could not create tickets.
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("ALTER TABLE server_ticket ALTER COLUMN is_private SET DEFAULT false")


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0160_remove_flarum_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(keep_default_in_database, migrations.RunPython.noop),
    ]
