# Generated by Django 4.2.2 on 2026-09-30 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0161_ticket_is_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="upvoters",
            field=models.ManyToManyField(
                blank=True, related_name="upvoted_tickets", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
