# Generated by Django 4.2.2 on 2026-09-30 16:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0163_ticket_category_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="razorpaytransaction",
            name="notes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="PaymentAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Shown to payers at checkout and to the account's viewers.",
                        max_length=255,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in the webhook URL and the page URL.", unique=True
                    ),
                ),
                (
                    "key_id",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^rzp_(test|live)_\\w+$",
                                "A Razorpay key ID starts with rzp_test_ or rzp_live_.",
                            )
                        ],
                    ),
                ),
                ("key_secret_encrypted", models.TextField(editable=False)),
                ("webhook_secret_encrypted", models.TextField(blank=True, editable=False)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="An inactive account takes no new orders but is still synced. Its viewers still see its payments.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "viewers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="People from the association who may see its payments in the Hub.",
                        related_name="viewable_payment_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="payment_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="server.paymentaccount",
            ),
        ),
        migrations.AddField(
            model_name="razorpaytransaction",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="server.paymentaccount",
            ),
        ),
    ]
