---
name: Fly Deploy (Metabase)
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy Metabase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy -c fly.metabase.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STAGING }}
