---
name: Fly Scale
on:
  workflow_dispatch:
    inputs:
      cpu:
        type: choice
        description: CPU Size
        options:
          - 2
          - 4
          - 8
      gunicorn:
        type: choice
        description: Gunicorn servers
        options:
          - 4
          - 8
          - 12
      hardLimit:
        type: choice
        description: Hard limit on connections
        options:
          - 100
          - 200
          - 400
      softLimit:
        type: choice
        description: Soft limit on connections
        options:
          - 75
          - 150
          - 300
jobs:
  scale:
    name: Scale up or down hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Replace cpu size
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "shared-cpu-[0-9]+x"
          replace: "shared-cpu-${{github.event.inputs.cpu}}x"
          include: "fly.toml"
      - name: Replace gunicorn servers
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "-w [0-9]+"
          replace: "-w ${{github.event.inputs.gunicorn}}"
          include: "deploy/start.sh"
      - name: Replace hard limit
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "hard_limit = [0-9]+"
          replace: "hard_limit = ${{github.event.inputs.hardLimit}}"
          include: "fly.toml"
      - name: Replace soft limit
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "soft_limit = [0-9]+"
          replace: "soft_limit = ${{github.event.inputs.softLimit}}"
          include: "fly.toml"
      - name: Get current unix timestamp
        id: timestamp
        uses: release-kit/unix-timestamp@v1
      - uses: EndBug/add-and-commit@v9
        with:
          new_branch: fly-scale-${{steps.timestamp.outputs.timestamp}}
          message: "vm: Scale"
